### ISSUE TITLE
Uniforms changing faction after death.

### ISSUE THREAD

**Issue by tbajas** [A3Armory/A3A_A3Wasteland.Tanoa#1]
Have had this happen a couple of times while on independent, with both lush and jungle ghillies. After getting killed I will return to recover my gear and my ghillie will have switched to nato or csat. Have been able to reproduce every time I die with a ghillie, 5/5, always on independent. In game name is AWACS

**Comment by codexGW** [comment]
Thanks for the report. Post reports here. Use Altis unless it's specific to that map like the mission.sqm or mapConfig. https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues It might not be fixed for awhile because AgentRev is busy and hes the only one really fixing anything.

Post any bugs specific to our changes or addons here unless they are map specific.
https://github.com/A3Armory/A3A_A3Wasteland.Altis/issues
